### ISSUE TITLE
two shades of black

### ISSUE THREAD

**Issue by robx** [diagrams/diagrams-rasterific#42]
I'm trying to switch out the diagrams backend of https://github.com/robx/puzzle-draw from cairo to rasterific. Works fine, but this introduces some artifacts in the output that seem like a bug.

In the example below, the thin grid lines are 1 pixel wide solid black lines. At the grid vertices, there is one pixel of color `#0d0d0d`, which used to be solid black with cairo. The grid lines are constructed from individual segments between vertices, with default linecap, that end nicely on pixel centers. I can fix this shade of black by change the linecap to square, but that breaks the dashing (for some other puzzle types), so I'd prefer to avoid that. I'd be happy to break this down to a more reduced example if necessary.

This is with diagrams-rasterific 1.4 and rasterific 0.7.2.1.

![lits-example](https://user-images.githubusercontent.com/132113/37045722-e2f7450a-2166-11e8-8b3c-dccbd580b55c.png)

**Comment by byorgey** [comment]
Thanks for the report!  @Twinside , any thoughts?

**Comment by Twinside** [comment]
I should look into it, I would guess that it's an overflow somewhere when blending the pixels. It will be a really fun unit test to write :]

**Comment by byorgey** [comment]
Closed by #46 .
