### ISSUE TITLE
PDF output seems to stroke things it shouldn't

### ISSUE THREAD

**Issue by robx** [diagrams/diagrams-rasterific#43]
Not quite sure what this is, or whether this should be filed against rasterific proper. Anyhow:

I see frames in PDF output that shouldn't be there.

rasterific png:
![doppelblock-example](https://user-images.githubusercontent.com/132113/37114372-756a9c34-2248-11e8-8e6b-2f3a4d93b182.png)

old cairo pdf, top left corner:
![screen shot 2018-03-07 at 20 44 14](https://user-images.githubusercontent.com/132113/37114400-8ba2312e-2248-11e8-8a79-72defb7fc5d0.png)

rasterific pdf, top left corner:
![screen shot 2018-03-07 at 20 44 03](https://user-images.githubusercontent.com/132113/37114408-9053147c-2248-11e8-8bf2-b7736f82e396.png)

The rasterific version has a frame around the whole diagram, as well as around the gray area. (That is placed using `frame`.) But also the text seems a lot heavier (using SVGFonts, stroked with `lwG 0`), as if the path was stroked after all.

(As an extra issue, the PDF comes out square, but maybe that's me passing the wrong options? Happy to file a separate issue for that if you want.)

**Comment by robx** [comment]
@Twinside any idea?

**Comment by Twinside** [comment]
I didn't even had time to look at the other bug :(

To help me debug, I would need what diagrams send to Rasterific to tell if it's on Rasterific or diagrams-rasterific side (and that would help in the other case too :]

**Comment by Twinside** [comment]
This is a bug in Rasterific, last update on Hackage (in the next few minutes) will fix it

**Comment by byorgey** [comment]
Sounds like this can be closed then?
