### ISSUE TITLE
please upload 1.4.2 to hackage

### ISSUE THREAD

**Issue by robx** [diagrams/diagrams-rasterific#57]
hackage is still on 1.4.1.1, while 1.4.2 seems ready

**Comment by robx** [comment]
@byorgey ^

**Comment by byorgey** [comment]
Thanks for the nudge!  I hadn't forgotten.  I've been working through all the diagrams packages (in topological dependency order) and getting them updated.  `diagrams-rasterific` is one of the next ones on the list.

**Comment by robx** [comment]
Alright, thanks then, and sorry for bugging you!

**Comment by byorgey** [comment]
No need to apologize!  Intermittent bugging is still useful. =)

**Comment by byorgey** [comment]
`diagrams-rasterific-1.4.2` is now on Hackage.  Sorry for the very long delay!

**Comment by robx** [comment]
Thank you!
