### ISSUE TITLE
Add Ability to Customize PDF DPI

### ISSUE THREAD

**Issue by prikhi** [diagrams/diagrams-rasterific#58]
[This line](https://github.com/diagrams/diagrams-rasterific/blob/3acafb78d269bc9d3e7fe9087717cf04dbb38979/src/Diagrams/Backend/Rasterific.hs#L425) fixes the DPI of PDF files to `96`. 

It'd be nice to have the ability to customize this, maybe through a `renderPDFWithDPI` function?

If there is interest in supporting this, I will submit a PR.

**Comment by byorgey** [comment]
Makes sense, I see no reason not to be able to customize it.  A PR would be welcome.

**Comment by prikhi** [comment]
Cool, PR opened @ #59
