### ISSUE TITLE
Rounding fontSize causes problems

### ISSUE THREAD

**Issue by jeffreyrosenbluth** [diagrams/diagrams-rasterific#7]
Rasterific expects an integral font size. Sometimes the rounding error is particularly noticeable, especially when the units are `Local`. a `fontSize` of < `Locaal 0.5` can be rounded to zero.

https://github.com/diagrams/diagrams-rasterific/blob/master/src/Diagrams/Backend/Rasterific.hs#L429

**Comment by Twinside** [comment]
I'm bumping this ticket as FontyFruity 0.5 (only available in the GitHub repository) switched to a Float representation. The important point maybe not mentioned enough in this ticket is that FontyFruity and Rasterific use the "Point" (pt) for the font size. The point unit being much bigger than "pixel" and DPI dependant, having fractional units is interesting.

I want to finish my SVG renderer before releasing fonty&rasterific on hackage, and I'll come back when things have stabilized a bit on this topic.

**Comment by bergey** [comment]
Thanks for clarifying.  I understand now - fractional pt sizes are very useful.
